kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: 'email'
      group_by: ['alertname']
      group_wait: 10s
      repeat_interval: 30m
    receivers:
    - name: 'email'
      email_configs:
      - to: 'krpsanthoshkumar@gmail.com, santhoshkumar.r@bsfdv.com'
        send_resolved: true
        from: krpsanthoshkumar@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: 'krpsanthoshkumar@gmail.com'
        auth_identity: 'krpsanthoshkumar@gmail.com'
        auth_password: 'kntcdhpnhhcyoiqa'