apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-storage
  namespace: monitoring
  labels:
    app: prometheus
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/santhoshkumarravi/Documents/Santhosh/Internal Project/internal-project-kubernetes/internal-project-kubernetes/prometheus"